name: ✨ Feature Request
description: Suggest a new feature or enhancement for X-Filamenta-Python
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to have..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: "Alternatively, we could..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application does this relate to?
      options:
        - Authentication / 2FA
        - Admin Panel
        - User Management
        - i18n / Translations
        - Database / Migrations
        - API / Endpoints
        - UI / Frontend
        - Documentation
        - Deployment
        - Testing
        - Performance
        - Security
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Examples
      description: Provide specific use cases or examples of how this feature would be used
      placeholder: "For example, when a user..."
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Design Ideas
      description: If applicable, add mockups, wireframes, or design ideas (drag and drop images here)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for similar feature requests and found none
          required: true
        - label: I have provided all required information above
          required: true
        - label: This is a feature request, not a bug report or question
          required: true
        - label: I am willing to contribute to this feature (optional)
          required: false
