"""
Comprehensive . gitignore Generator

Purpose: Generate comprehensive .gitignore for Flask + HTMX project
Description: Creates a complete .gitignore covering Python, Flask, IDEs, OS files, and more

File:  scripts/setup/generate_gitignore.py | Repository: X-Filamenta-Python
Created: 2025-12-30
Last modified (Git): TBD | Commit: TBD

Distributed by:  XAREMA | Coder:  AleGabMar
App version: 0.0.1-Alpha | File version: 1.0.0

License:  AGPL-3.0-or-later
SPDX-License-Identifier:  AGPL-3.0-or-later

Copyright (c) 2025 XAREMA.  All rights reserved. 

Metadata:
- Status: Stable
- Classification: Internal

Usage:
    # Generate .gitignore (prompts if exists)
    python scripts/setup/generate_gitignore.py

    # Force overwrite existing .gitignore
    python scripts/setup/generate_gitignore.py --force
"""

import argparse
from pathlib import Path


GITIGNORE_TEMPLATE = """# Flask + Python Project . gitignore
# Generated by setup script

# ============================================
# Python
# ============================================
__pycache__/
*. py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# ============================================
# Virtual Environment
# ============================================
venv/
env/
ENV/
env.bak/
venv.bak/
.venv/

# ============================================
# Flask
# ============================================
instance/
.webassets-cache
.flask_session/
flask_session/

# ============================================
# Environment Variables
# ============================================
.env
.env.local
.env.*. local
*. env

# ============================================
# Database
# ============================================
*.db
*.sqlite
*.sqlite3
*.db-shm
*.db-wal

# ============================================
# IDE / Editors
# ============================================
# VSCode
.vscode/
*. code-workspace

# PyCharm / IntelliJ IDEA
.idea/
*. iml
*. iws
*.ipr

# Sublime Text
*. sublime-project
*.sublime-workspace

# Vim
*.swp
*.swo
*~

# ============================================
# Operating System
# ============================================
# macOS
.DS_Store
. AppleDouble
.LSOverride
Icon
._*

# Windows
Thumbs.db
ehthumbs.db
Desktop. ini
$RECYCLE.BIN/

# Linux
*~
.directory
. Trash-*

# ============================================
# Logs
# ============================================
*.log
logs/
*.log.*
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# ============================================
# Testing
# ============================================
.pytest_cache/
.coverage
htmlcov/
.tox/
.nox/
coverage.xml
*.cover
. hypothesis/

# ============================================
# Build / Distribution
# ============================================
node_modules/
npm-debug.log
yarn-error.log

# ============================================
# Temporary Files
# ============================================
*.tmp
*.temp
*.bak
*.swp
*.swo

# ============================================
# Project Specific
# ============================================
# Add your project-specific ignores here
uploads/
migrations/versions/*. pyc

# Analysis reports (if sensitive)
# Analysis_reports/*-CONFIDENTIAL.md
"""


def generate_gitignore(output_path: Path, overwrite: bool = False) -> None:
    """
    Generate . gitignore file. 
    
    Args:
        output_path: Path to . gitignore file
        overwrite: If True, overwrite existing file without prompting
    """
    if output_path.exists() and not overwrite:
        print(f"⚠️  . gitignore already exists at {output_path}")
        response = input("Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Aborted.")
            return
    
    output_path.write_text(GITIGNORE_TEMPLATE. strip(), encoding='utf-8')
    print(f"✓ Generated .gitignore at {output_path}")
    print("\n📝 Next steps:")
    print("  1. Review the file")
    print("  2. Customize the 'Project Specific' section")
    print("  3. Commit to repository")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Generate .gitignore for Flask project',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        '--force',
        action='store_true',
        help='Overwrite existing .gitignore without prompting'
    )
    
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('. gitignore'),
        help='Output path (default: . gitignore in current directory)'
    )
    
    args = parser.parse_args()
    
    generate_gitignore(args.output, overwrite=args.force)


if __name__ == '__main__': 
    main()